version: '3.7'
services:
  notificador:
    build: .
    container_name: notificador
    volumes:
      - ./appdata:/appdata
    networks:
      - kafka_network
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network 

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Alterado para 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Mantendo compatível com Django
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka_network
    depends_on:
      - zookeeper]

  django:
    build: .
    container_name: django
    networks:
      - kafka_network
    depends_on:
      - kafka
    entrypoint: ["/app/wait-for-kafka.sh"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]


 
