# Generated by Django 5.1.3 on 2025-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
