# Generated by Django 5.1.3 on 2025-02-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_mesa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pessoas',
        ),
    ]
